export { getMotorcyclesByType } from './getMotorcycleByType.query';
export { getMotorcycleTypesPage } from './getMotorcycleTypesPage.query';
export { getNewsPage } from './getNewsPage.query';
export { GetNewsPostsQuery } from './getNewsPosts.query';
export { GetPreloadedNewsPostsQuery } from './getPreloadedNewsPosts.query';
export { GetMotocycle } from './motocycle.query';
export { GetMotocycles } from './motocycles.query';
export { GetPage } from './page.query';
export { GET_HEADER } from './technical.query';
